cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='index'),
    path('success/', views.success, name='success'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('hx_menu_item/', views.hx_menu_item, name='hx_menu_item'),
    path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),

]

commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# amazon s3 photo storage needs to be added to the project
# now we can add the following to the settings.py file: static files

urlpatterns = [
    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .cart import Cart
from django.contrib.auth.decorators import login_required
from product.models import Product
from django.conf import settings
# Create your views here.
def add_to_cart(request, product_id):
    cart = Cart(request) # create a new cart object passing it the request object
    cart.add(product_id) # add a product to the cart
    print('cart', cart.cart)
    return render(request, 'cart/menu_item.html') # redirect the user to the cart details page

def cart(request):
  
    return render(request, 'cart/index.html')

def success(request):
    return render(request, 'cart/success.html')


def update_cart(request, product_id, action):
    cart = Cart(request)
    if action == 'increment':
      
        cart.add(product_id, 1, True) # add one to the quantity
        cart.save()
    else:
      
        cart.add(product_id, -1, True) # remove one from the quantity
        # check if the quantity is 0, if so, remove the item from the cart
          # if the quantity is now 0, remove the item from the cart
        if cart.get_item(product_id) is None or cart.get_item(product_id)['quantity'] == 0:
            cart.remove(product_id)
       
    # get the product object from the database including the product id
    product = Product.objects.get(pk=product_id)
    # get the product object photo set
    photo = product.photo_set.first() # get the first photo in the set from the database
    
    quantity = cart.get_item(product_id)['quantity'] # get the quantity of the updated product


    item = {
        'product': {
        'id': product_id,
        'name': product.name,
        'image_url': photo.url,
        'price': product.price,
        },
        'id': product_id,
        'total_price': (product.price * quantity),
        'quantity': quantity,
    }
    print('item.image_url', item['product']['image_url'])
    response = render(request, 'cart/partials/cart_item.html', {'item': item})

    response['HX-Trigger'] = 'update-menu-cart' # trigger the cart.update event on the client side

    return response


@login_required
def checkout(request):
    # get products in cart and their prices
    total_cost = 0
    cart = Cart(request)
    # get the total cost of all items in the cart
    for item in cart:
        total_cost += item['total_price']
    
    print('total_cost', total_cost)

    pub_key = settings.STRIPE_PUBLIC_KEY
    # where is this used
    return render(request, 'cart/checkout.html', {'pub_key': pub_key, 'total_cost': total_cost})

def hx_menu_item(request):
    return render(request, 'cart/menu_item.html')



def hx_cart_total(request):
    cart = Cart(request)
    total_cost = 0
    # total_cost = cart.get_total_cost()
    # find the sum of the total cost of all items in the cart
    for item in cart:
        total_cost += item['total_price']
    return render(request, 'cart/partials/cart_total.html', {'total_cost': total_cost})

cart/templates/cart/checkout.html
{% extends 'core/base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
   
                <div class="products w-full lg:w-3/4">
                    <h1 class="mb-5 text-3xl ">Checkout</h1>
                    <div class="w-full pr-6">
                    <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                        <h2 class="mb-5 uppercase text-lg">Shipping Information</h2>
                        <div class="flex space-x-6">
                            <div class="w-1/2 mb-4">
                                <label for="" class="inline-block mb-2">First Name</label>
                                <input name="first_name" type="text" class="w-full p-5 rounded-xl" value="{{ request.user.first_name }}">
                            </div>  
                            <div class="w-1/2 mb-4">
                                <label for="" class="inline-block mb-2">Last Name</label>
                                <input name="last_name" type="text" class="w-full p-5 rounded-xl" value="{{ request.user.last_name }}">
                            </div>   
                        </div>
                        <div class="mb-4">
                            <label for="" class="inline-block mb-2">Address</label>
                            <input name="address" type="text" class="w-full p-5 rounded-xl">
                        </div>
                        <div class="flex space-x-6">
                            <div class="w-1/2 mb-4">
                                <label for="" class="inline-block mb-2">Zip Code</label>
                                <input name="zipcode" type="text" class="w-full p-5 rounded-xl">
                            </div>  
                            <div class="w-1/2 mb-4">
                                <label for="" class="inline-block mb-2">City</label>
                                <input name="place" type="text" class="w-full p-5 rounded-xl">
                            </div>   
                        </div>
                    </div> 
                    <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                        <h2 class="mb-5 uppercase text-lg">Contact Information</h2>
                        <div class="mb-4">
                            <label for="" class="inline-block mb-2">Email</label>
                            <input name="email" type="email" class="w-full p-5 rounded-xl" value="{{ request.user.email }}">
                        </div>
                        <div class="mb-4">
                            <label for="" class="inline-block mb-2">Phone</label>
                            <input name="phone" type="phone" class="w-full p-5 rounded-xl">
                        </div>
                    </div> 
                    <div class="mb-6 p-6 bg-gray-100 rounded-xl text-red-300" id = 'errors'>
                        
                    </div>
                    <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                        <h2 class="mb-5 uppercase text-lg">Payment Information</h2>
                    </div> 
                    </div>
                </div>
            <div class="summary w-full w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
                <h2 class="uppercase text-lg mb-5">Summary</h2>
                <div class="mb-6 flex justify-between">
                    <span class="font-semibold">Total</span>
                    <span>${{ total_cost }}</span>
                </div>
                <button 
                onclick={buy(event)}
                class="inline-block px-8 py-4 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">Confirm Checkout</button>
        
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="application/javascript" src="https://js.stripe.com/v3/"></script>

<script>
   
    let elementErrors = document.getElementById('errors');
    
    function validateForm(data) {
    let errors = []
    // check if all fields are filled
    for (const [key, value] of Object.entries(data)) {
        if (value === '') {
            errors.push(key)
        }
    }
    if (errors.length > 0) {
        alert(`Please fill in the following fields: ${errors.join(', ')}`)
        // put the errors in the html at the bottom
        // let errorHTML = '<ul>'
        // add "Errors" to the start of the list
        let errorHTML = '<ul><li>Errors: Please fill in the following fields</li>'
        for (let i = 0; i < errors.length; i++) {
            errorHTML += `<li>${errors[i]}</li>`
        }
        elementErrors.innerHTML = errorHTML + '</ul>'
    } else {
        elementErrors.innerHTML = ''

    }
    return errors
}

    

    function buy(event) {
        event.preventDefault();


        let data = {
            'first_name': document.querySelector('input[name="first_name"]').value, 
            'last_name': document.querySelector('input[name="last_name"]').value,
            'address': document.querySelector('input[name="address"]').value,
            'zipcode': document.querySelector('input[name="zipcode"]').value,
            'place': document.querySelector('input[name="place"]').value,
            'email': document.querySelector('input[name="email"]').value,
            'phone': document.querySelector('input[name="phone"]').value,
            'csrfmiddlewaretoken': '{{ csrf_token }}'
        }
        let errors = validateForm(data)

        console.log(errors)

        


        if (errors.length) {
            console.log("errors", errors)
        } else {
            var stripe = Stripe("{{ pub_key }}"); 
            // how to import Stripe? 
            // https://stripe.com/docs/js/including
            fetch('/order/start_order/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}',
                },
                credentials: 'same-origin', // include, *same-origin, omit
                body: JSON.stringify(data)
            })
            .then(function(response) {
                return response.json();
            })
            .then(function(session) {
                return stripe.redirectToCheckout({ sessionId: session.session.id });
            })
            .then(function(result) {
                if(result.error) {
                    alert(result.error.message)
                }
            })
            .catch(function(error) {
                console.log('Error:', error)
            });
        }

        return false;
    }
</script>
{% endblock %}

cart/templates/cart/index.html
{% extends 'core/base.html' %}

{% block content %}
<div class="max-w-6xl mx-auto py-6 px-6 xl:px-0">
    <div class="products grid grid-cols-1 gap-6">
        {% for item in cart %}
            {% include 'cart/partials/cart_item.html' %}
        {% endfor %}
    </div>
    <div class="summary w-full lg:w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
        <h2 class="uppercase text-lg mb-5">Summary</h2>
        <div class="mb-6 flex justify-between">
            <span class="font-semibold">Total</span>
            <!-- <span>${{ cart.get_total_cost }}</span> -->
            <span
                hx-get="{% url 'cart:hx_cart_total' %}"
                hx-trigger="update-menu-cart from:body"
                hx-swap="innerHTML"
            >
            {% include 'cart/partials/cart_total.html' %}
            
        </span>
        </div>
        <a href="{% url 'cart:checkout' %}" class="inline-block px-8 py-4 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">Checkout</a>
    </div>
</div>

{% endblock %}

cart/templates/cart/menu_item.html
<a href="{% url 'cart:index' %}" id = "menu-cart-button" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"><span class="p-2 m-1 -top-4 -right-3 bg-indigo-500 text-white text-xs rounded-full">{{cart|length}}</span>Cart</a>
<!-- make a link to url 'cart/index' -->
<!-- make a cart button with value of cart length in the top right corner -->
<!-- write a link to index.html -->

cart/templates/cart/success.html
{% extends 'core/base.html' %}

{% block title %}Success{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
   
                <div class="products w-full lg:w-3/4">
                    <h1 class="mb-5 text-3xl ">Success</h1>
                    <h2 class="mb-5 text-3xl ">Thank you!</h2>
                    
                    <p>Your order is on the way!</p>
                    </div>
            </div>
{% endblock %}