cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='index'),
    path('success/', views.success, name='success'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('hx_menu_item/', views.hx_menu_item, name='hx_menu_item'),
    path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),

]

commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# amazon s3 photo storage needs to be added to the project
# now we can add the following to the settings.py file: static files

urlpatterns = [
    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:product_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm
# auth_views is a module that contains all the views for authentication
# we are importing the LoginView class from the module


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    # need log out, but redirect to login page not admin page
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('myaccount/', views.myaccount, name='myaccount'), 
    path('myaccount/edit/', views.edit_myaccount, name='edit_myaccount'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.products, name='products'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk>/delete_photo/', views.delete_photo, name='delete_photo'),

    # path to add_photo
    path('<int:pk>/add_photo', views.add_photo, name='add_photo'),

]

core/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    WATCHES = 'Watches'
    NATURE_PHOTOGRAPHY = 'Nature Photography'
    CLOTHES = 'Clothes'
    
    DEFAULT_CATEGORIES = [
        (WATCHES, 'Watches'),
        (NATURE_PHOTOGRAPHY, 'Nature Photography'),
        (CLOTHES, 'Clothes'),
    ]
    name = models.CharField(max_length=255, choices=DEFAULT_CATEGORIES, default=NATURE_PHOTOGRAPHY)
    # give default category: watches, nature_photos, clothes 
    

    # give categories: watches, phones, laptops, shoes, clothes, etc.

    class Meta:
        ordering = ('name',) # ordering by name
        verbose_name_plural = 'Categories' # plural name
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True) # blank=True, null=True 
    price = models.FloatField( blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    image = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name
    
class Photo(models.Model):
   url = models.CharField(max_length=200)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)

   def __str__(self):
      return f"Photo for product_id: {self.product.id} @{self.url}"

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    # override the default fields
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'your username',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'your password',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))


class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'your username',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'your email address',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'your password',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'confirm your password',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    

core/views.py
from django.shortcuts import render, redirect
# import models from product app, not from core app
from product.models import Product, Category
from .forms import SignupForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    products = Product.objects.filter(is_sold=False)[0:6] # get first 6 products
    categories = Category.objects.all()
    return render(request, 'core/index.html', { 
        'categories': categories,
        'products': products
        })

def contact(request):
    return render(request, 'core/contact.html')

# here's the view for the myaccount page, how can I call it in another app? explain: 
@login_required
def myaccount(request):
    return render(request, 'core/myaccount.html')


@login_required
def edit_myaccount(request):
    if request.method == "POST":
 

        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.save()

        return redirect('/myaccount')

    return render(request, 'core/edit_myaccount.html')


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    else:     
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form
        })

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Commerce</title>
    </head>

    <body>
        <nav class="py-4 px-4 lg:py-6 lg:px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Commerce</a>
            <button id="menu-toggle" class="lg:hidden text-xl font-semibold">
                &#9776; Menu
            </button>
            <div id="menu-items" class="hidden lg:flex space-x-6">
                <!-- Rest of the code -->
                <a href="{% url 'product:products' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                <a href="{% url 'product:new' %}" class="text-lg font-semibold hover:text-gray-500">New product</a>

                    {% if request.user.is_authenticated %}
                        
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-emerald-500 text-white rounded-xl hover:bg-emerald-700">Inbox</a>
                    <a href="{% url 'core:myaccount' %}" class="px-6 py-3 text-lg font-semibold bg-emerald-500 text-white rounded-xl hover:bg-emerald-700">My Account</a>

                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <!-- cart link -->
                    <span
                        class="ml-6 px-3 py-2 text-lg font-semibold text-gray-800 rounded-full inline-flex items-center"
                        hx-get="{% url 'cart:hx_menu_item' %}"
                        hx-trigger="update-menu-item from:body" 
                        hx-swap="innerHTML"
                    >
                        {% include 'cart/menu_item.html' %}
                        
                    </span>

                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
                    
                    {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-emerald-500 text-white rounded-xl hover:bg-emerald-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                    {% endif %}    
            </div>
        </nav>
        <div id="mobile-menu" class="hidden lg:hidden px-6 py-6 space-y-6">
            <!-- Mobile menu items -->
            <a href="{% url 'product:products' %}" class="block text-lg font-semibold hover:text-gray-500">Browse</a>
            <a href="{% url 'product:new' %}" class="block text-lg font-semibold hover:text-gray-500">New product</a>
        
            {% if request.user.is_authenticated %}
                <a href="{% url 'conversation:inbox' %}" class="block px-6 py-3 text-lg font-semibold bg-emerald-500 text-white rounded-xl hover:bg-emerald-700">Inbox</a>
                <a href="{% url 'core:myaccount' %}" class="block px-6 py-3 text-lg font-semibold bg-emerald-500 text-white rounded-xl hover:bg-emerald-700">My Account</a>
                <a href="{% url 'dashboard:index' %}" class="block px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                <span
                    class="ml-6 px-3 py-2 text-lg font-semibold text-gray-800 rounded-full inline-flex items-center"

                    hx-get="{% url 'cart:hx_menu_item' %}"
                    hx-trigger="update-menu-item from:body" 
                    hx-swap="innerHTML"
                >
                    {% include 'cart/menu_item.html' %}
                </span>
                <a href="{% url 'core:logout' %}" class="block px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="block px-6 py-3 text-lg font-semibold bg-emerald-500 text-white rounded-xl hover:bg-emerald-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="block px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
        



</div>
        <div class="px-6 py-6 ">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">A place to sell prints of your best photography!</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-emerald-500 hover:text-emerald-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-emerald-500 hover:text-emerald-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-emerald-500 hover:text-emerald-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-emerald-500 hover:text-emerald-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
        <!-- htmx -->
        <script src="https://unpkg.com/htmx.org@1.7.0"></script>
        
        {% block scripts %}
        {% endblock %}
        <script>
            document.getElementById('menu-toggle').addEventListener('click', function() {
                document.getElementById('mobile-menu').classList.toggle('hidden');
            });
        </script>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}


{% block content %}
    
    <h1>The CONTACT page</h1>
    <p>Some content</p>
{% endblock %}

core/templates/core/edit_myaccount.html
{% extends 'core/base.html' %}

{% block title %}Edit My Account{% endblock %}

{% block content %}
<div class="w-1/2 my-6 bg-gray-100 rounded-xl">
    <h1 class ="mb-5 text-3xl">Edit Account</h1>

    <form method="POST" class="space-y-3">
        {% csrf_token %}
        <div>
            <label>First name</label>
            <input name="first_name" value="{{ request.user.first_name }}" type="'text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>
        <div>
            <label>Last name</label>
            <input name="last_name" value="{{ request.user.first_name }}" type="'text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>
        <div>
            <label>Username</label>
            <input name="username" value="{{ request.user.username }}" type="'text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>
        <div>
            <label>Email</label>
            <input name="email" value="{{ request.user.email }}" type="'text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>
        <div>
            <button class="py-4 px-6 rounded-xl text-white bg-purple-500">Update</button>
        </div>
    </form>

</div>

{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest products</h2>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-3">
            {% for product in products %}
                <div>
                    <a href="{% url 'product:detail' product.id %}">
                        {% for photo in product.photo_set.all %}
                        <div>
                            <img src="{{ photo.url }}" class="rounded-t-xl">
                        </div>
                        {% endfor %} 
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ product.name }}</h2>
                            <p class="text-gray-500">Price: {{ product.price }}</p>
                        </div>
                    </a>
            {% if request.user.is_authenticated and request.user != product.created_by %}
            <a 
            href="#" 
            class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl"
            hx-get="{% url 'cart:add_to_cart' product.id %}"
            hx-target="#menu-cart-button"
            hx-swap="outerHTML"
            >Add to Cart</a>
        {% elif not request.user.is_authenticated %}
            
        {% else %}
            
        {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
<!-- SPLIT here -->
   
    <!-- Split -->
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.products.count }} products</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 bg-gray-100 rounded-xl ">
    <h1 class="text-center mb-6 text-3xl">Log in</h1>
    <form action="." method="POST" class="px-3 py-3">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {{ form.non_field_errors}}
        
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Username</label>
            {{ form.username }}
        </div>
        <div class="mb-3 flex flex-col">
           
            {{ form.email }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Password</label>
            {{ form.password }}
        </div>
       

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>

        {% endif %}
        <button type="submit" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log in</button>
    </form>
</div>
{% endblock %}

core/templates/core/myaccount.html
{% extends 'core/base.html' %}

{% block title %}My Account{% endblock %}

{% block content %}
<div class="w-1/2 my-6 bg-gray-100 rounded-xl">
    <h1 class ="mb-5 text-3xl">My Account</h1>
    <!-- user full name -->
    <div class="mb-4">
        <!-- list name, username, and email from request.user -->
        <strong>Name: </strong><p class="text-xl">{{ request.user.first_name }} {{ request.user.last_name }}</p>
        <strong>Username: </strong><p class="text-xl">{{ request.user.username }}</p>
        <strong>Email: </strong><p class="text-xl mb-6">{{ request.user.email }}</p>
        <a href="{% url 'core:edit_myaccount' %}" class="mt-4 py-4 px-6 rounded-xl text-white bg-purple-500">Edit</a>
        <!-- url path to edit_myaccount -->

    </div>
    <hr>
    <h2 class="my-6 text-xl">My orders</h2>
    <!-- list all orders from request.user -->
    {% for order in request.user.orders.all %}

    <div class="w-full mb-6 p-6 flex flex-wrap bg-gray-100 rounded-xl">
        {% for item in order.items.all %}
        <div class="mb-6 flex justify-between">
            <a href="#">
                <p class="text-xl">Order #</p>
                <p class="text-xl">Date:</p>
                <p class="text-xl">{{ order.status }}</p>
                <p class="text-xl">{{ order.total }}</p>
            </a>
        </div>
    <div class="mb-6 w-full">
        <div class="product mb-6 flex pr-6">
            <a href="#" class="w-1/4">
                <img src="{{ item.product.image }}" alt="product_image" class="hover:shadow-lg rounded-xl">
            </a>

            <div class="w-3/4 pl-6">
                <div class="flex justify-between">
                    <a href="#" class="text-lg">Product Name: {{item.product.name}}</a>
                    <p class="mb-6 pt-1 text-gray-400">Price: {{ item.get_total_price }}</p>
                </div>

                <hr>

                <div class="mt-6">
                    Quantity: {{ item.quantity }}
                </div>
            
            </div>
        </div>
        {% endfor %}
        </div>
        <p class="text-lg">Date: {{ order.created_at }}</p>
        <p class="text-lg">Total: ${{ order.get_total_price }} </p>
        </div>
{% endfor %}
</div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 bg-gray-100 rounded-xl ">
    <h1 class="text-center mb-6 text-3xl">Sign up</h1>
    <form action="." method="POST" class="px-3 py-3">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {{ form.non_field_errors}}
        
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Username</label>
            {{ form.username }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Password</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Repeat Password</label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>

        {% endif %}
        <button type="submit" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</button>
    </form>
</div>
{% endblock %}