cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='index'),
    path('success/', views.success, name='success'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('hx_menu_item/', views.hx_menu_item, name='hx_menu_item'),
    path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),

]

commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# amazon s3 photo storage needs to be added to the project
# now we can add the following to the settings.py file: static files

urlpatterns = [
    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:product_pk>/', views.new_conversation, name='new'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.products, name='products'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk>/delete_photo/', views.delete_photo, name='delete_photo'),

    # path to add_photo
    path('<int:pk>/add_photo', views.add_photo, name='add_photo'),

]

product/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    WATCHES = 'Watches'
    NATURE_PHOTOGRAPHY = 'Nature Photography'
    CLOTHES = 'Clothes'
    
    DEFAULT_CATEGORIES = [
        (WATCHES, 'Watches'),
        (NATURE_PHOTOGRAPHY, 'Nature Photography'),
        (CLOTHES, 'Clothes'),
    ]
    name = models.CharField(max_length=255, choices=DEFAULT_CATEGORIES, default=NATURE_PHOTOGRAPHY)
    # give default category: watches, nature_photos, clothes 
    

    # give categories: watches, phones, laptops, shoes, clothes, etc.

    class Meta:
        ordering = ('name',) # ordering by name
        verbose_name_plural = 'Categories' # plural name
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True) # blank=True, null=True 
    price = models.FloatField( blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    image = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name
    
class Photo(models.Model):
   url = models.CharField(max_length=200)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)

   def __str__(self):
      return f"Photo for product_id: {self.product.id} @{self.url}"

product/forms.py
from django import forms

from .models import Product

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewProductForm(forms.ModelForm):
    # add a new field for the image file
    

    class Meta:
        model = Product
        fields = ('category', 'name', 'description', 'price',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            
        }



class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'is_sold')
        # widgets is a dictionary that contains the fields as keys and the widgets as values
        widgets = {
            'name': forms.TextInput(attrs={
            'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
            'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
            'class': INPUT_CLASSES
            }),
           
            # is_sold is a boolean field, so we need to use a checkbox
            'is_sold': forms.CheckboxInput(),
        }
    

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q # Q is a shortcut for OR queries
from .models import Product, Category, Photo
from django.contrib.auth.decorators import login_required
from .forms import NewProductForm, EditProductForm
import uuid
import boto3
from django.shortcuts import get_object_or_404

S3_BASE_URL = "https://s3.us-east-2.amazonaws.com/"
BUCKET = "commerce-nov8"

# Create your views here.

def products(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0) # 0 is the default value if category_id is not found
    categories = Category.objects.all()
    products = Product.objects.filter(is_sold=False)
    
    
    if category_id:
        products = products.filter(category_id=category_id) # filter by category_id = category_id from the url


    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query)) # Q is a shortcut for OR queries
        # import Q from django.db.models


    
    return render(request, 'product/products.html', {
        'products': products,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })



def detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'product/detail.html', {
        'product': product,
        'related_products': related_products
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_by = request.user
            product.save()
            
            return redirect('product:detail', pk=product.id)
        else: 
            form = NewProductForm()

    form = NewProductForm()
    
    return render(request, 'product/form.html', {
        'form': form,
        'title': 'New Product'
    })

@login_required
def edit(request, pk):
    print('line 63',pk)
    product = get_object_or_404(Product, pk=pk, created_by=request.user)
    # get_object_or_404 is a shortcut that will return a 404 error if the object is not found
    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)
        print("form",form.is_valid())
        if form.is_valid():
            product = form.save()
            
            product.save()


            return redirect('product:detail', pk=product.id)
    else: 
            form = EditProductForm(instance=product)

    
    
    return render(request, 'product/form.html', {
        'form': form,
        'title': 'Update Product'
    })

@login_required
def delete(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)
    product.delete()
    return redirect('dashboard:index')

@login_required
def delete_photo(request, pk):
    photo = get_object_or_404(Photo, pk=pk)

    # delete the photo from S3 and remove the image property from the product
    s3 = boto3.client('s3')
    s3.delete_object(Bucket=BUCKET, Key=photo.url[photo.url.rfind('/')+1:]) # delete the object from S3 using the url property of the photo object
    photo.delete()
    

    return redirect('product:detail', pk=pk)



@login_required
def add_photo(request, pk):
    product = Product.objects.get(pk=pk)
    

    # collect photo submitted by the user
    photo_file= request.FILES.get('photo-file', None)
    # if photo file present
    if photo_file:
       
     # set up a s3 client object - obj w/methods for working with s3
        s3 = boto3.client('s3')
        
    # create a unique name for the file
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # upload the file to AWS S3
        try:
              # generate a unique url for the image
              # save the url as a new instance of the Photo model
             
              s3.upload_fileobj(photo_file, BUCKET, key)
              url = f"{S3_BASE_URL}{BUCKET}/{key}"
              Photo.objects.create(url=url, product=product, pk=pk)
              print(product)
            # add an image property to the product
              product.image = url
            #   update the product in the database
              product.save()
              print(product, product.image)

        except Exception as error:
            print('An error occurred uploading file to S3: ', error)
         
        # if there's an error, print it out

    # redirect to the product detail page

    return redirect('product:detail', pk=pk)

# add a mixin to check if the user is logged in, protect the class-based views

product/templates/product/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6 mb-3">
        <div class="col-span-3">
            <img src="{{ product.image.url }}" class="rounded-xl">
        {% for photo in product.photo_set.all %}
        
            <img src="{{ photo.url }}" class="rounded-xl" alt="{{product.name}}">
        {% empty %} 
        
            <h2>No Photos Uploaded Yet</h2>
        {% endfor %}
        <form action="{% url 'product:add_photo' product.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <button class="bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded">
                Upload Photo
              </button>
        </form>
        <form action="{% url 'product:delete_photo' product.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
           
            <button class="bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded">
                Delete Photo
              </button>
        </form>

        </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ product.name }}</h1>
        <p class="text-gray-500"><strong>Price: {{ product.price }}</strong></p>
        <p class="text-gray-500"><strong>Seller: {{ product.created_by.username }}</strong></p>
        {% if product.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description:</strong><br> {{ product.description }}</p>
        {% endif %}
        {% if request.user == product.created_by %}
        <div class="mt-6 p-6 bg-white rounded-xl">
            <p>This is your product!</p>
            <a href="{% url 'product:edit' product.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>

            <a href="{% url 'product:delete' product.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>

        </div>
        {% else %}
        <a 
        href="#" 
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl"
        hx-get="{% url 'cart:add_to_cart' product.id %}"
        hx-target="#menu-cart-button"
        hx-swap="outerHTML"
        >Add to Cart</a>
        <a href="{% url 'conversation:new' product.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-orange-500 text-white hover:bg-orange-700 rounded-xl">Contact Seller</a>
        {% endif %}
    </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related products</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for product in related_products %}
                <div>
                    <a href="{% url 'product:detail' product.id %}">
                        {% for photo in product.photo_set.all %}
                        <div>
                            <img src="{{ photo.url }}" class="rounded-t-xl">
                        </div>
                        {% endfor %} 

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ product.name }}</h2>
                            <p class="text-gray-500">Price: {{ product.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

product/templates/product/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{title}}</h1>
 <!-- upload photo div -->
<form  method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-y-4">
        {{ form.as_p }}
      
    </div>
   
    
    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}

        {{ form.non_field_errors }}
    </div>

    {% endif %}
    <button type="submit" class="mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">{{title}}</button>
</form>

{% endblock %}

product/templates/product/products.html
{% extends 'core/base.html' %} 

{% block title %}Products{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'product:products' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>
            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <ul>
                {% for category in categories %}
                <!-- 
                    explain if category.id == category_id # if the category id is equal to the category id
                    then add the class bg-gray-200
                
                -->
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200 {% endif %}">
                        <a href="{% url 'product:products' %}?query={{ query }}&category={{category.id}}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            <hr class="my-6">
            <p class="font-semibold">Clear Filters</p>

            <ul>
                <li><a href="{% url 'product:products'%}" class="mt-2 py-4 px-8 inline-block rounded-xl bg-yellow-500 text-white">Clear</a></li>
            </ul>

        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-1 lg:grid-cols-3 gap-3">

                {% for product in products %}
                    <div>
                        <a href="{% url 'product:detail' product.id %}">
                            {% for photo in product.photo_set.all %}
                                <div>
                                    <img src="{{ photo.url }}" class="rounded-t-xl">
                                </div>
                            {% endfor %} 
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ product.name }}</h2>
                                <p class="text-gray-500">Price: {{ product.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        </div>
    </div>


{% endblock %}