cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='index'),
    path('success/', views.success, name='success'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('hx_menu_item/', views.hx_menu_item, name='hx_menu_item'),
    path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),

]

commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# amazon s3 photo storage needs to be added to the project
# now we can add the following to the settings.py file: static files

urlpatterns = [
    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .cart import Cart
from django.contrib.auth.decorators import login_required
from product.models import Product
from django.conf import settings
# Create your views here.
def add_to_cart(request, product_id):
    cart = Cart(request) # create a new cart object passing it the request object
    cart.add(product_id) # add a product to the cart
    print('cart', cart.cart)
    return render(request, 'cart/menu_item.html') # redirect the user to the cart details page

def cart(request):
  
    return render(request, 'cart/index.html')

def success(request):
    return render(request, 'cart/success.html')


def update_cart(request, product_id, action):
    cart = Cart(request)
    if action == 'increment':
      
        cart.add(product_id, 1, True) # add one to the quantity
        cart.save()
    else:
      
        cart.add(product_id, -1, True) # remove one from the quantity
        # check if the quantity is 0, if so, remove the item from the cart
          # if the quantity is now 0, remove the item from the cart
        if cart.get_item(product_id) is None or cart.get_item(product_id)['quantity'] == 0:
            cart.remove(product_id)
       
    # get the product object from the database including the product id
    product = Product.objects.get(pk=product_id)
    # get the product object photo set
    photo = product.photo_set.first() # get the first photo in the set from the database
    
    quantity = cart.get_item(product_id)['quantity'] # get the quantity of the updated product


    item = {
        'product': {
        'id': product_id,
        'name': product.name,
        'image_url': photo.url,
        'price': product.price,
        },
        'id': product_id,
        'total_price': (product.price * quantity),
        'quantity': quantity,
    }
    print('item.image_url', item['product']['image_url'])
    response = render(request, 'cart/partials/cart_item.html', {'item': item})

    response['HX-Trigger'] = 'update-menu-cart' # trigger the cart.update event on the client side

    return response


@login_required
def checkout(request):
    # get products in cart and their prices
    total_cost = 0
    cart = Cart(request)
    # get the total cost of all items in the cart
    for item in cart:
        total_cost += item['total_price']
    
    print('total_cost', total_cost)

    pub_key = settings.STRIPE_PUBLIC_KEY
    # where is this used
    return render(request, 'cart/checkout.html', {'pub_key': pub_key, 'total_cost': total_cost})

def hx_menu_item(request):
    return render(request, 'cart/menu_item.html')



def hx_cart_total(request):
    cart = Cart(request)
    total_cost = 0
    # total_cost = cart.get_total_cost()
    # find the sum of the total cost of all items in the cart
    for item in cart:
        total_cost += item['total_price']
    return render(request, 'cart/partials/cart_total.html', {'total_cost': total_cost})

cart/templates/cart/partials/cart_item.html
{% if item.quantity > 0 %}
<div class="product mb-6 flex pr-6" id="cart-item-{{ item.product.id }}">
    <!-- <img class="hover:shadow-lg rounded-xl h-48 w-48 object-cover flex-shrink-0" src="{{ item.image_url }}" alt="{{ product.name }}"> -->
{% if item.image_url %}
    <img class="hover:shadow-lg rounded-xl h-48 w-48 object-cover flex-shrink-0" src="{{ item.image_url }}" alt="{{ product.name }}">
{% else %}
    <img class="hover:shadow-lg rounded-xl h-48 w-48 object-cover flex-shrink-0" src="{{ item.product.image_url }}" alt="{{ product.name }}">
{% endif %}

    <div class="w-3/4 pl-6">
        <div class="flex justify-between">
            <a href="#" class="text-lg">{{ item.product.name }}</a>
            <span class="mb-6 pt-1 text-gray-600">${{ item.total_price }}</span>

        </div>
        <hr>
        <div class="quantity mt-6 flex items-center space-x-4">
        <a 
            href="#"
            class="p-3 bg-gray-100"
            hx-get="{% url 'cart:update_cart' item.product.id 'decrement'  %}"
            hx-target="#cart-item-{{ item.product.id }}"
            hx-swap="outerHTML"
            >
            -
        </a>
            <span 
            class="text-lg" 
            id ="cart-item-{{item.product.id}}"
            hx-trigger="update-menu-item from:body"
            hx-swap="innerHTML"
            >{{ item.quantity }} </span>
        <a 
            href="#"
            class="p-3 bg-gray-100"
            hx-get="{% url 'cart:update_cart' item.product.id 'increment' %}"
            hx-target="#cart-item-{{ item.product.id }}"
            hx-swap="outerHTML"
            >
            +
        </a>

        </div>

    </div>
</div>
{% endif %}

cart/templates/cart/partials/cart_total.html
${{ cart.get_total_cost }}